name: github-pages-dev 
on:
  push:
    branches:
      - develop
permissions:
  contents: write
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: documentation/
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: /root/.local/bin/uv sync 
      - run: PDF=1 /root/.local/bin/uv run mike deploy -u dev